//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSSoft.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSSoft.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; is already registered..
        /// </summary>
        public static string Exception_AlreadyExistedItem_Format {
            get {
                return ResourceManager.GetString("Exception_AlreadyExistedItem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; is already registered..
        /// </summary>
        public static string Exception_AlreadyRegisteredProperty_Format {
            get {
                return ResourceManager.GetString("Exception_AlreadyRegisteredProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It must be at least step 1..
        /// </summary>
        public static string Exception_AtLeastStep1 {
            get {
                return ResourceManager.GetString("Exception_AtLeastStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values between 0 and 1 must be used..
        /// </summary>
        public static string Exception_Between0and1 {
            get {
                return ResourceManager.GetString("Exception_Between0and1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set self to parent folder..
        /// </summary>
        public static string Exception_CannotBeSetItSelfAsParent {
            get {
                return ResourceManager.GetString("Exception_CannotBeSetItSelfAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Child folders in folders can not be set as parents..
        /// </summary>
        public static string Exception_ChildFolderCannotBeSetAsParent {
            get {
                return ResourceManager.GetString("Exception_ChildFolderCannotBeSetAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyclic dependency found..
        /// </summary>
        public static string Exception_CyclicDependency {
            get {
                return ResourceManager.GetString("Exception_CyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty string can not be used as a name..
        /// </summary>
        public static string Exception_EmptyStringCannotBeUsedAsName {
            get {
                return ResourceManager.GetString("Exception_EmptyStringCannotBeUsedAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indestructible Object..
        /// </summary>
        public static string Exception_IndestructibleObject {
            get {
                return ResourceManager.GetString("Exception_IndestructibleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can not include special characters \ / : * ? &lt; &gt; | etc..
        /// </summary>
        public static string Exception_InvalidName {
            get {
                return ResourceManager.GetString("Exception_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid name..
        /// </summary>
        public static string Exception_InvalidName_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid path..
        /// </summary>
        public static string Exception_InvalidPath {
            get {
                return ResourceManager.GetString("Exception_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is invalid path..
        /// </summary>
        public static string Exception_InvalidPath_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidPath_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; can not be used as property..
        /// </summary>
        public static string Exception_InvalidPropertyType_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidPropertyType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only &apos;{1}&apos; in &apos;{0}&apos; phase has progressed..
        /// </summary>
        public static string Exception_LessStep_Format {
            get {
                return ResourceManager.GetString("Exception_LessStep_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path &apos;{0}&apos; could not be found..
        /// </summary>
        public static string Exception_NotFoundDirectory_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundDirectory_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder &apos;{0}&apos; could not be found..
        /// </summary>
        public static string Exception_NotFoundFolder_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundFolder_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item &apos;{0}&apos; could not be found..
        /// </summary>
        public static string Exception_NotFoundItem_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundItem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property &apos;{0}&apos; does not exist..
        /// </summary>
        public static string Exception_NotFoundProperty_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0}&apos; could not be found..
        /// </summary>
        public static string Exception_NotFoundType_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path to the file does not include the parent path..
        /// </summary>
        public static string Exception_NotIncludedParentPath {
            get {
                return ResourceManager.GetString("Exception_NotIncludedParentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &apos;{0} is not supported..
        /// </summary>
        public static string Exception_NotSupportedType_Format {
            get {
                return ResourceManager.GetString("Exception_NotSupportedType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The step exceeds the specified number of times&apos; {0}&apos;..
        /// </summary>
        public static string Exception_OverStep_Format {
            get {
                return ResourceManager.GetString("Exception_OverStep_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folder with same name exists in parent folder..
        /// </summary>
        public static string Exception_SameFolderInParent {
            get {
                return ResourceManager.GetString("Exception_SameFolderInParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item with same name exists in parent folder..
        /// </summary>
        public static string Exception_SameItemInParent {
            get {
                return ResourceManager.GetString("Exception_SameItemInParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scheduler is already running..
        /// </summary>
        public static string Exception_SchedulerIsAlreadyRunning {
            get {
                return ResourceManager.GetString("Exception_SchedulerIsAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The calling thread cannot access this object because a different thread owns it..
        /// </summary>
        public static string Exception_ThreadCannotAccess {
            get {
                return ResourceManager.GetString("Exception_ThreadCannotAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &apos;{0}&apos; is not defined..
        /// </summary>
        public static string Exception_UndefinedValue_Format {
            get {
                return ResourceManager.GetString("Exception_UndefinedValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not rename objects whose unique name property is set..
        /// </summary>
        public static string Exception_UniqueObjectCannotRename {
            get {
                return ResourceManager.GetString("Exception_UniqueObjectCannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A folder without a name can not be set up by a parent folder..
        /// </summary>
        public static string Exception_UnnamedFolderCannotHaveParent {
            get {
                return ResourceManager.GetString("Exception_UnnamedFolderCannotHaveParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed..
        /// </summary>
        public static string Message_Completed {
            get {
                return ResourceManager.GetString("Message_Completed", resourceCulture);
            }
        }
    }
}
