//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ntreev.Library.Properties {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ntreev.Library.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Item &apos;{0}&apos; is already registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AlreadyExistedItem_Format {
            get {
                return ResourceManager.GetString("Exception_AlreadyExistedItem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property &apos;{0}&apos; is already registered.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_AlreadyRegisteredProperty_Format {
            get {
                return ResourceManager.GetString("Exception_AlreadyRegisteredProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Values between 0 and 1 must be used.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_Between0and1 {
            get {
                return ResourceManager.GetString("Exception_Between0and1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unable to set self to parent folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CannotBeSetItSelfAsParent {
            get {
                return ResourceManager.GetString("Exception_CannotBeSetItSelfAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Child folders in folders can not be set as parents.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_ChildFolderCannotBeSetAsParent {
            get {
                return ResourceManager.GetString("Exception_ChildFolderCannotBeSetAsParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cyclic dependency found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_CyclicDependency {
            get {
                return ResourceManager.GetString("Exception_CyclicDependency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Empty string can not be used as a name.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_EmptyStringCannotBeUsedAsName {
            get {
                return ResourceManager.GetString("Exception_EmptyStringCannotBeUsedAsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indestructible Object과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_IndestructibleObject {
            get {
                return ResourceManager.GetString("Exception_IndestructibleObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name can not include special characters \ / : * ? &lt; &gt; | etc.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidName {
            get {
                return ResourceManager.GetString("Exception_InvalidName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is invalid name과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidName_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidName_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Invalid path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidPath {
            get {
                return ResourceManager.GetString("Exception_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   &apos;{0}&apos; is invalid path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidPath_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidPath_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &apos;{0}&apos; can not be used as property.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_InvalidPropertyType_Format {
            get {
                return ResourceManager.GetString("Exception_InvalidPropertyType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path &apos;{0}&apos; could not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotFoundDirectory_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundDirectory_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder &apos;{0}&apos; could not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotFoundFolder_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundFolder_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item &apos;{0}&apos; could not be found.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotFoundItem_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundItem_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Property &apos;{0}&apos; does not exist.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotFoundProperty_Format {
            get {
                return ResourceManager.GetString("Exception_NotFoundProperty_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file does not include the parent path.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotIncludedParentPath {
            get {
                return ResourceManager.GetString("Exception_NotIncludedParentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type &apos;{0} is not supported.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_NotSupportedType_Format {
            get {
                return ResourceManager.GetString("Exception_NotSupportedType_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder with same name exists in parent folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameFolderInParent {
            get {
                return ResourceManager.GetString("Exception_SameFolderInParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Item with same name exists in parent folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_SameItemInParent {
            get {
                return ResourceManager.GetString("Exception_SameItemInParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value &apos;{0}&apos; is not defined.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UndefinedValue_Format {
            get {
                return ResourceManager.GetString("Exception_UndefinedValue_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can not rename objects whose unique name property is set.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UniqueObjectCannotRename {
            get {
                return ResourceManager.GetString("Exception_UniqueObjectCannotRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A folder without a name can not be set up by a parent folder.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Exception_UnnamedFolderCannotHaveParent {
            get {
                return ResourceManager.GetString("Exception_UnnamedFolderCannotHaveParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Completed.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        public static string Message_Completed {
            get {
                return ResourceManager.GetString("Message_Completed", resourceCulture);
            }
        }
    }
}
